sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

install:
  - haxelib install actuate
  - haxelib install bin-packing
  - haxelib install Sure

script:
  - haxe DistanceFieldGeneratorDemo.hxml debug.hxml
  - haxe DistanceFieldGeneratorDemo.hxml release.hxml

# Deploy the generated demo using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: bin/release
  github_token: $GITHUB_API_KEY
  target-branch: gh-pages